name: docker
on:
  push:
    branches: [ master ]

jobs:
  build_push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t minionflo/sys_restapi .
      - run: docker push minionflo/sys_restapi